@baseURL = http://localhost:3000

### Rota pública (acesso livre)

GET {{baseURL}}/public/home
Content-Type: application/json

### Cadastro de novo usuário

POST {{baseURL}}/auth/register
Content-Type: application/json

{
 "email": "novo@ifrs.edu.br",
 "password": "senha123",
 "role": "user"
}

### Login do novo usuário (pegar o token gerado abaixo)

POST {{baseURL}}/auth/login
Content-Type: application/json

{
 "email": "novo@ifrs.edu.br",
 "password": "senha123"
}

### Login do usuário comum (usuário já existente no banco)

POST {{baseURL}}/auth/login
Content-Type: application/json

{
 "email": "usuario@ifrs.edu.br",
 "password": "123456"
}

### Login do administrador (usuário já existente no banco)

POST {{baseURL}}/auth/login
Content-Type: application/json

{
 "email": "admin@ifrs.edu.br",
 "password": "admin123"
}

### Acesso ao painel (rota protegida, requer token de qualquer usuário autenticado)

GET {{baseURL}}/protected/dashboard
Authorization: Bearer {{}}

### Acesso à área admin (rota protegida, requer token de usuário com role "admin")

GET {{baseURL}}/protected/admin
Authorization: Bearer {{}}